# -*- coding: utf-8 -*-
"""formate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIUmTIV1WfZ_N3DC1-jaw6WfDm-cNwML
"""

!pip install jinja2 weasyprint

from google.colab import files
uploaded = files.upload()

import os
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML, CSS

# Function to get user inputs
def get_user_inputs():
    # You can replace these with actual inputs
    inputs = {
        "project_name": "AI Research Project",
        "student_name": "John Doe",
        "guide_name": "Dr. Smith",
        "college_name": "ABC College",
        "academic_year": "2024-2025",
        "logo_base64": "your_base64_string_here"
    }
    return inputs


# Generate PDF
def generate_pdf(data, template_file, output_pdf, css_file):
    # Load the HTML template
    template_dir = os.path.dirname(template_file)  # Get directory of template file
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template(os.path.basename(template_file))  # Get filename from path

    # Render the HTML with dynamic data
    rendered_html = template.render(data)

    # Load the CSS file
    css = CSS(filename=css_file)

    # Generate PDF with CSS styling
    HTML(string=rendered_html).write_pdf(output_pdf, stylesheets=[css])
    print(f"PDF generated successfully: {output_pdf}")


if __name__ == "__main__":
    # Get user inputs
    user_data = get_user_inputs()

    # Template and output file
    template_file = "/content/sample_data/template.html"  # Path to your HTML template
    css_file = "/content/sample_data/style.css"  # Path to your CSS file
    output_pdf = "Dynamic_Project_Report.pdf"

    # Generate the PDF
    generate_pdf(user_data, template_file, output_pdf, css_file)